import os


MESSENGER_VERIFY_TOKEN = os.getenv("MESSENGER_VERIFY_TOKEN")
MESSENGER_PAGE_ACCESS_TOKEN = os.getenv("MESSENGER_PAGE_ACCESS_TOKEN")
MESSENGER_WEBHOOK_PREFIX = os.getenv("MESSENGER_WEBHOOK_PREFIX", "/messenger")
MESSENGER_WEBHOOK_ENDPOINT = os.getenv("MESSENGER_WEBHOOK_ENDPOINT", "/webhook")

KOKORO_FAST_API_HOST = os.getenv("KOKORO_FAST_API_HOST")
KOKORO_FAST_API_VERIFY_SSL = os.getenv("KOKORO_FAST_API_IGNORE_SSL", "true").strip().lower() == "false"

PORT = int(os.getenv("PORT", "8000"))
