FROM golang:1.24 AS base
WORKDIR /app

# install hot reload tool
RUN go install github.com/cosmtrek/air@latest

COPY go.mod .
RUN go mod download

COPY . .

# run with air for live reload
CMD ["air"]
