[project]
name = "practice-fb-messaging-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "ollama>=0.4.8",
    "uvicorn>=0.34.2",
]
