name: Build & Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    uses: jhjcpishva/ci-workflows/.github/workflows/docker-build.yml@main
    with:
      platforms: linux/amd64,linux/arm64
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
